version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: '06:00'
  open-pull-requests-limit: 99
- package-ecosystem: gradle
  directory: "/selenium4-junit4"
  schedule:
    interval: daily
    time: '06:00'
  open-pull-requests-limit: 99
- package-ecosystem: gradle
  directory: "/selenium4-junit5"
  schedule:
    interval: daily
    time: '06:00'
  open-pull-requests-limit: 99
- package-ecosystem: gradle
  directory: "/selenium4-testng"
  schedule:
    interval: daily
    time: '06:00'
  open-pull-requests-limit: 99
- package-ecosystem: gradle
  directory: "/selenium4-seljup"
  schedule:
    interval: daily
    time: '06:00'
  open-pull-requests-limit: 99
