name: 'Setup'
description: 'Setup workflow'

inputs:
  os:
    description: 'Operating system'
    required: true
  java:
    description: 'JDK version'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.java }}
    - name: Start Xvfb on Linux
      if: inputs.os == 'ubuntu-latest'
      run: Xvfb :99 &
    - name: Install Edge on Linux
      if: inputs.os == 'ubuntu-latest'
      run: |
        curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
        sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
        sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge-stable.list'
        sudo rm microsoft.gpg
        sudo apt update && sudo apt install microsoft-edge-stable
