name: Dependabot auto-merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.1.1
        with:
          github-token: "${{ secrets.WDM_GITHUBTOKEN }}"
      - name: Enable auto-merge for Dependabot PRs
        if: ${{contains(steps.metadata.outputs.dependency-names, 'my-dependency') && steps.metadata.outputs.update-type == 'version-update:semver-patch'}}
        run: |
          gh pr merge --auto --squash --merge "$PR_URL" --body="Co-authored-by: Boni Garcia <boni.garcia@uc3m.es>"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          WDM_GITHUBTOKEN: ${{secrets.WDM_GITHUBTOKEN}}