name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DISPLAY: :99
  WDM_GITHUBTOKEN: ${{ secrets.WDM_GITHUBTOKEN }}

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        project: [ junit4, junit5, junit5-seljup, testng ]
        build-tool: [ mvn, gradle ]
        os: [ ubuntu-latest ]
        java: [ 11 ]

    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v2
    - name: Set up Java ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Start Xvfb on ${{ matrix.os }}
      if: matrix.os == 'ubuntu-latest'
      run: Xvfb :99 &
    - name: Run ${{ matrix.project }} tests with ${{ matrix.build-tool }}
      run: |
        cd selenium-webdriver-${{ matrix.project }}
        ${{ matrix.build-tool }} test

