name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DISPLAY: :99
  WDM_GITHUBTOKEN: ${{ secrets.WDM_GITHUBTOKEN }}

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        project: [ junit4, junit5, junit5-seljup, testng ]
        build-tool: [ mvn, gradle ]
        os: [ ubuntu-latest ]
        java: [ 11 ]

    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v2
    - name: Set up Java ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Start Xvfb on ${{ matrix.os }}
      if: matrix.os == 'ubuntu-latest'
      run: Xvfb :99 &
    - name: Install Edge on ${{ matrix.os }}
      if: matrix.os == 'ubuntu-latest'
      run: |
        curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
        sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
        sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge-stable.list'
        sudo rm microsoft.gpg
        sudo apt update && sudo apt install microsoft-edge-stable
    - name: Run ${{ matrix.project }} tests with ${{ matrix.build-tool }}
      run: |
        cd selenium-webdriver-${{ matrix.project }}
        ${{ matrix.build-tool }} test

